; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; Master Chair Configuration (WiFi AP + Web Interface + Bluetooth Master)
[env:master]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_flags = 
  -DCHAIR_MASTER
  -DMASTER_PULSE_PIN=32
  -DMASTER_ENABLE_PIN=12
  -DMASTER_DIR_PIN=26
  -DCORE_DEBUG_LEVEL=0
  -O2
lib_deps =
  me-no-dev/AsyncTCP@^1.1.1
  esphome/ESPAsyncWebServer-esphome@^3.3.0
  links2004/WebSockets@^2.4.2
  ESPmDNS

; Slave Chair Configuration (WiFi Client + HTTP Server + Stepper Control)
[env:slave]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = 
  -DCHAIR_SLAVE
  -DSLAVE_PULSE_PIN=32
  -DSLAVE_ENABLE_PIN=12
  -DSLAVE_DIR_PIN=26
lib_deps =
  me-no-dev/AsyncTCP@^1.1.1
  esphome/ESPAsyncWebServer-esphome@^3.3.0



  ;slave-/dev/cu.usbserial-0001
